### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nalsai** [Nalsai/summarizer#1]
- [x] CI Pipeline
- [x] Keyboard shortcuts
  - ctrl w to close
  - ...
- [x] Fix filechooser
- [ ] Einstellungsmenü
- [ ] Windows build (incomplete on [setup.py](https://github.com/Nalsai/summarizer/tree/setup.py) branch)
- [ ] Tokenisierung (auch für unterschiedliche Sprachen)
- [ ] Stats: Sätze, Wörter, Tokens, Stop words, Zeichen
